
CREATE  DATABASE banhang ;
USE banhang;

CREATE TABLE KHACHHANG (
	MAKH INT PRIMARY KEY ,
	HOTEN VARCHAR(50) ,
	DIACHI VARCHAR(50),
	SODT INT ,
	NGSINH DATE ,
	DOANHSO DECIMAL(10,2),
	NGDK DATE 
);

ALTER TABLE KHACHHANG 
ADD LOAIKH TINYINT ;


CREATE TABLE NHANVIEN(
	MANV INT PRIMARY KEY ,
	HOTEN VARCHAR(50) , 
	NGVL DATE ,
	SODT INT 
	
);

CREATE TABLE SANPHAMS(
	MASP INT PRIMARY KEY ,
	TENSP VARCHAR(50),
	DVT VARCHAR(50),
	NUOCSX VARCHAR(50),
	GIA DECIMAL(10,2)
);
ALTER TABLE SANPHAMS 
ADD GHICHU VARCHAR(29) AFTER TENSP;

ALTER TABLE SANPHAMS 
MODIFY GHICHU VARCHAR(100);

ALTER  TABLE SANPHAMS
DROP COLUMN GHICHU ;

CREATE TABLE HOADON (
    SOHD INT PRIMARY KEY,
    NGHD DATE,
    MAKH INT,
    MANV INT,
    TRIGIA DECIMAL(10,2),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE CTHD (
   	SOHD INT  ,
	MASP INT ,
	SL   INT ,
	PRIMARY KEY (SOHD,MASP),
 	FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
 	FOREIGN KEY (MASP) REFERENCES SANPHAMS(MASP)
 );
-- dung bang de luu gia tri
CREATE TABLE LOAIKH (
    ID TINYINT PRIMARY KEY,
    TENLOAI VARCHAR(20)
);

INSERT INTO LOAIKH VALUES
(1, 'Vang lai'),
(2, 'Thuong xuyen'),
(3, 'Vip');


-- don vi san pham 
ALTER TABLE SANPHAMS
ADD CONST1RAINT CHK_DVT  CHECK (DVT IN ('cay','hop','cai','quyen','chuc'));


 gia ban san pham tu 500d tro len 
ALTER TABLE SANPHAMS 
ADD CONSTRAINT CK_giaban CHECK (GIA >=500);

-- Mỗi lần mua hàng, khách hàng phải mua ít nhất 1 sản phẩm




-- ngay dki cua khach phai lon hon ngay sinh cua khach

ALTER TABLE KHACHHANG
ADD CONSTRAINT CHK_NGDK_NGSINH CHECK (NGDK > NGSINH);

-- moi hoa dnon phao co 1 chi tiet hoa don
DELIMITER //
CREATE TRIGGER trg_CHECK_MINIMUM_PRODUCTS
BEFORE INSERT ON CTHD
FOR EACH ROW
BEGIN
    DECLARE total_products INT;
    
    SELECT COUNT(*) INTO total_products
    FROM CTHD
    WHERE CTHD.SOHD = NEW.SOHD;

    IF total_products < 1 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Mỗi hóa đơn phải có ít nhất một chi tiết hóa đơn.';
    END IF;
END;
//
DELIMITER ;


-- Trigger để cập nhật doanh số khi có hóa đơn mới
DELIMITER //
CREATE TRIGGER trg_UPDATE_CUSTOMER_PURCHASE
AFTER INSERT ON HOADON
FOR EACH ROW
BEGIN
    UPDATE KHACHHANG
    SET KHACHHANG.DOANHSO = KHACHHANG.DOANHSO + NEW.TRIGIA
    WHERE KHACHHANG.MAKH = NEW.MAKH;
END;
//
DELIMITER ;







